version: "3.8"

services:

  db:
    image: mysql
    container_name: db_cont
    ports:
      - "3306:3306"    
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  django_app:
    build:
      context: .
    image: django_app
    container_name: django_cont
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    environment:
      - DB_NAME=test_db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=3306
      - DB_HOST=db_cont
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
  nginx:
    build: 
      context: ./nginx
    image: custom_nginx
    container_name: nginx_cont
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
